# Generated by Django 4.2.7 on 2025-07-22 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(upload_to='mous/')),
                ('clauses', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOU',
                'verbose_name_plural': 'MOUs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('max_access_count', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='mous.mou')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_organization', models.CharField(max_length=255)),
                ('partner_email', models.EmailField(max_length=254)),
                ('partner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_pdf', models.FileField(blank=True, null=True, upload_to='partner_submissions/')),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='mous.sharelink')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('accessed', 'Accessed'), ('signed', 'Signed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('pdf_uploaded', 'PDF Uploaded'), ('link_generated', 'Link Generated'), ('link_accessed', 'Link Accessed')], max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='mous.mou')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
